apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: brev
  namespace: aap
  labels:
    team: aap
spec:
  ttl: 1h # Fjern denne om appen tas i bruk igjen
  image: {{image}}
  accessPolicy:
    outbound:
      external:
        - host: 948n95rd.api.sanity.io
  envFrom:
    - secret: kelvin-env-local
  ingresses: 
    - https://aap-brev.intern.dev.nav.no
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: brev
  resources:
    limits:
      cpu: 1000m
    requests:
      cpu: 500m
      memory: 512Mi
  replicas:
    cpuThresholdPercentage: 90
    disableAutoScaling: true
    max: 1
    min: 1
  liveness:
    path: /actuator/live
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  readiness:
    path: /actuator/ready
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  prometheus:
    enabled: true
    path: /actuator/metrics
  secureLogs:
    enabled: true
