apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: brev
  namespace: aap
  labels:
    team: aap
spec:
  image: {{image}}
  replicas:
    cpuThresholdPercentage: 90
    disableAutoScaling: true
    max: 1
    min: 1
  accessPolicy:
    inbound:
      rules:
        - application: aap-saksbehandling
    outbound:
      external:
        - host: 948n95rd.api.sanity.io
  resources:
    limits:
      cpu: 1000m
    requests:
      cpu: 500m
      memory: 512Mi
  liveness:
    path: /actuator/live
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  readiness:
    path: /actuator/ready
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  prometheus:
    enabled: true
    path: /actuator/metrics
  secureLogs:
    enabled: true
  envFrom:
    - secret: kelvin-env-local