apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: brev
  namespace: aap
  labels:
    team: aap
    sub: brev
spec:
  image: {{image}}
  ingresses:
    - "https://aap-brev.intern.dev.nav.no"
  replicas:
    cpuThresholdPercentage: 90
    max: 2
    min: 1
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  observability:
    autoInstrumentation:
      enabled: true
      runtime: "java"
    logging:
        destinations:
            - id: elastic
            - id: loki
  gcp:
    sqlInstances:
      - type: POSTGRES_16
        tier: db-custom-1-3840
        diskAutoresize: true
        highAvailability: true
        pointInTimeRecovery:
        databases:
          - name: brev
  liveness:
    path: /actuator/live
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  readiness:
    path: /actuator/ready
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  prometheus:
    enabled: true
    path: /actuator/metrics
  azure:
    application:
      enabled: true
      allowAllUsers: true
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: behandlingsflyt
          permissions:
            roles:
              - "bestill-brev"
              - "hent-brev"
        - application: paw-patrol
        - application: dokumentinnhenting
          permissions:
            roles:
              - "dokumentinnhenting-api"
        - application: azure-token-generator
          namespace: nais
          cluster: dev-gcp
          permissions:
            roles:
              - "bestill-brev"
              - "hent-brev"
              - "dokumentinnhenting-api"
    outbound:
      external:
        - host: dokarkiv-q2.dev-fss-pub.nais.io
        - host: dokdistfordeling.dev-fss-pub.nais.io
        - host: saf-q2.dev-fss-pub.nais.io
        - host: pdl-api.dev-fss-pub.nais.io
      rules:
        - application: behandlingsflyt
        - application: brev-sanity-proxy
        - application: saksbehandling-pdfgen
        - application: nom-api
          namespace: nom
        - application: norg2
          namespace: org

  env:
    - name: INTEGRASJON_TILGANG_URL
      value: http://tilgang
    - name: INTEGRASJON_TILGANG_SCOPE
      value: api://dev-gcp.aap.tilgang/.default

    - name: INTEGRASJON_BEHANDLINGSFLYT_URL
      value: http://behandlingsflyt
    - name: INTEGRASJON_BEHANDLINGSFLYT_SCOPE
      value: api://dev-gcp.aap.behandlingsflyt/.default
    - name: INTEGRASJON_BEHANDLINGSFLYT_AZP
      value: dev-gcp:aap:behandlingsflyt

    - name: INTEGRASJON_DOKUMENTINNHENTING_AZP
      value: dev-gcp:aap:dokumentinnhenting

    - name: INTEGRASJON_BREV_SANITY_PROXY_URL
      value: http://brev-sanity-proxy
    - name: INTEGRASJON_BREV_SANITY_PROXY_SCOPE
      value: api://dev-gcp.aap.brev-sanity-proxy/.default

    - name: INTEGRASJON_SAKSBEHANDLING_PDFGEN_URL
      value: http://saksbehandling-pdfgen
    - name: INTEGRASJON_SAKSBEHANDLING_PDFGEN_SCOPE
      value: api://dev-gcp.aap.saksbehandling-pdfgen/.default

    - name: INTEGRASJON_DOKARKIV_URL
      value: https://dokarkiv-q2.dev-fss-pub.nais.io
    - name: INTEGRASJON_DOKARKIV_SCOPE
      value: api://dev-fss.teamdokumenthandtering.dokarkiv/.default

    - name: INTEGRASJON_DOKDISTFORDELING_URL
      value: https://dokdistfordeling.dev-fss-pub.nais.io
    - name: INTEGRASJON_DOKDISTFORDELING_SCOPE
      value: api://dev-fss.teamdokumenthandtering.dokdistfordeling/.default

    - name: INTEGRASJON_SAF_URL_GRAPHQL
      value: https://saf-q2.dev-fss-pub.nais.io/graphql
    - name: INTEGRASJON_SAF_SCOPE
      value: api://dev-fss.teamdokumenthandtering.saf/.default

    - name: INTEGRASJON_AZURE_TOKEN_GENERATOR_AZP
      value: dev-gcp:nais:azure-token-generator

    - name: INTEGRASJON_NOM_URL
      value: http://nom-api.nom/graphql
    - name: INTEGRASJON_NOM_SCOPE
      value: api://dev-gcp.nom.nom-api/.default

    - name: INTEGRASJON_NORG_URL
      value: http://norg2.org

    - name: INTEGRASJON_PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: INTEGRASJON_PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default

    - name: INTEGRASJON_REGOPPSLAG_URL
      value: https://regoppslag.dev-fss-pub.nais.io
    - name: INTEGRASJON_REGOPPSLAG_SCOPE
      value: api://dev-fss.regoppslag.teamdokumenthandtering/.default

    - name: INTEGRASJON_DOKDISTKANAL_URL
      value: https://dokdistkanal.dev-fss-pub.nais.io/rest/v1
    - name: INTEGRASJON_DOKDISTKANAL_SCOPE
      value: api://dev-fss.dokdistfordeling.teamdokumenthandtering/.default
