package no.nav.aap.brev.innhold

enum class KjentFaktagrunnlag {
    AAP_FOM_DATO,
    DAGSATS,
    BEREGNINGSTIDSPUNKT,
    BEREGNINGSGRUNNLAG,
    GRUNNLAG_BEREGNING_AAR_1_AARSTALL,
    GRUNNLAG_BEREGNING_AAR_2_AARSTALL,
    GRUNNLAG_BEREGNING_AAR_3_AARSTALL,
    GRUNNLAG_BEREGNING_AAR_1_INNTEKT,
    GRUNNLAG_BEREGNING_AAR_2_INNTEKT,
    GRUNNLAG_BEREGNING_AAR_3_INNTEKT,
    FRIST_DATO_11_7,
    BARNETILLEGG_SATS,
    GRADERT_DAGSATS,
    GRADERT_BARNETILLEGG,
    GRADERT_DAGSATS_INKLUDERT_BARNETILLEGG,
    BARNETILLEGG,
    ANTALL_BARN,
    MINSTE_AARLIG_YTELSE,
    MINSTE_AARLIG_YTELSE_UNDER_25AAR,
    AARLIG_YTELSE,
    SISTE_DAG_MED_YTELSE,
    SYKDOMSVURDERING,
    KRAVDATO_UFORETRYGD,
    DATO_AVKLART_FOR_JOBBSOK
}