package no.nav.aap.brev.innhold

enum class KjentFaktagrunnlag {
    FRIST_DATO_11_7,
    GRUNNLAG_BEREGNING_AAR_1_AARSTALL,
    GRUNNLAG_BEREGNING_AAR_2_AARSTALL,
    GRUNNLAG_BEREGNING_AAR_3_AARSTALL,
    GRUNNLAG_BEREGNING_AAR_1_INNTEKT,
    GRUNNLAG_BEREGNING_AAR_2_INNTEKT,
    GRUNNLAG_BEREGNING_AAR_3_INNTEKT,
}