package no.nav.aap.brev.innhold

enum class KjentKategori {
    HAR_BARNETILLEGG,
    HAR_FRADRAG_ANDRE_YTELSER,
    HAR_REDUKSJON_ARBEIDSGIVER,
    HAR_REFUSJONSKRAV_TJENESTEPENSJON,
    HAR_SAMORDNING_ANDRE_YTELSER,
    HAR_SAMORDNING_BARNEPENSJON,
    HAR_SAMORDNING_UFØRE,
    HAR_SYKESTIPEND,
}