package no.nav.aap.brev.innhold

enum class KjentKategori {
    HAR_BARNETILLEGG,
    HAR_FRADRAG_ANDRE_YTELSER,
    HAR_REDUKSJON_ARBEIDSGIVER,
    HAR_REFUSJONSKRAV_TJENESTEPENSJON,
    HAR_SAMORDNING_ANDRE_YTELSER,
    HAR_SAMORDNING_BARNEPENSJON,
    HAR_SAMORDNING_UFØRE,
    HAR_SYKESTIPEND,
    HAR_YRKESSKADE,
    BEREGNINGSUTFALL_SISTE_AAR,
    BEREGNINGSUTFALL_GJENNOMSNITT,
    BEREGNINGSUTFALL_MINSTESATS_OVER_25,
    BEREGNINGSUTFALL_MINSTESATS_UNDER_25,
    BEREGNINGSUTFALL_INNTEKT_OVER_6G,
    // Beregningstype (§11-19 standard, §11-28 uføre, §11-22 yrkesskade)
    BEREGNINGSTYPE_STANDARD,
    BEREGNINGSTYPE_UFØRE,
    BEREGNINGSTYPE_YRKESSKADE,
    BEREGNINGSTYPE_YRKESSKADE_UFØRE,
    // Beregningsmetode (siste år vs treårs gjennomsnitt)
    BEREGNINGSMETODE_SISTE_ÅR,
    BEREGNINGSMETODE_TREÅRS_GJENNOMSNITT,
    // Uføre-valgkategori (§11-28 fjerde ledd)
    UFØRE_VALG_UFORETIDSPUNKT,
    UFØRE_VALG_YTTERLIGERE_NEDSATT,
    UFØRE_VALG_YTTERLIGERE_NEDSATT_OKT_UFOREGRAD,
    // Yrkesskade-valgkategori (§11-22)
    YRKESSKADE_VALG_STANDARD_VINNER,
    YRKESSKADE_VALG_SYKEPENGEGRUNNLAG,
    YRKESSKADE_VALG_FORDEL_70_ELLER_MINDRE,
}
