package no.nav.aap.brev.innhold

enum class KjentKategori {
    HAR_BARNETILLEGG,
    HAR_FRADRAG_ANDRE_YTELSER,
    HAR_REDUKSJON_ARBEIDSGIVER,
    HAR_REFUSJONSKRAV_TJENESTEPENSJON,
    HAR_SAMORDNING_ANDRE_YTELSER,
    HAR_SAMORDNING_BARNEPENSJON,
    HAR_SAMORDNING_UFØRE,
    HAR_SYKESTIPEND,
    HAR_YRKESSKADE,
    HAR_OPPGITT_YRKESSKADE_MEN_INGEN_REGISTRERT,
    BEREGNINGSUTFALL_SISTE_AAR,
    BEREGNINGSUTFALL_GJENNOMSNITT,
    BEREGNINGSUTFALL_MINSTESATS_OVER_25,
    BEREGNINGSUTFALL_MINSTESATS_UNDER_25,
    BEREGNINGSUTFALL_INNTEKT_OVER_6G,
}
