package no.nav.aap.brev.prosessering

enum class ProsesseringStatus {
    STARTET,
    INNHOLD_HENTET,
    FAKTAGRUNNLAG_HENTET,
    BREVBESTILLING_LØST,
    BREV_FERDIGSTILT,
    JOURNALFORT,
    JOURNALPOST_VEDLEGG_TILKNYTTET,
    JOURNALPOST_FERDIGSTILT,
    DISTRIBUERT,
    FERDIG,
    AVBRUTT
}
