CREATE TABLE BREVBESTILLING
(
    REFERANSE               UUID                                        NOT NULL    PRIMARY KEY,
    BREV                    JSON                                        NULL,
    OPPRETTET_TID           TIMESTAMP(3)    DEFAULT CURRENT_TIMESTAMP   NOT NULL,
    OPPDATERT_TID           TIMESTAMP(3)    DEFAULT CURRENT_TIMESTAMP   NOT NULL,
    BEHANDLING_REFERANSE    UUID                                        NOT NULL,
    SPRAK                   TEXT                                        NOT NULL,
    BREVTYPE                TEXT                                        NOT NULL,
    PROSESSERING_STATUS     TEXT                                        NULL
);

CREATE UNIQUE INDEX UIDX_BREVBESTILLING_BEHANDLING_REFERANSE_BREVTYPE ON BREVBESTILLING (BEHANDLING_REFERANSE, BREVTYPE);

CREATE TABLE JOBB
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    STATUS        VARCHAR(50)  DEFAULT 'KLAR'            NOT NULL,
    TYPE          VARCHAR(50)                            NOT NULL,
    SAK_ID        BIGINT NULL,
    BEHANDLING_ID BIGINT NULL,
    PARAMETERS    TEXT NULL,
    PAYLOAD       TEXT NULL,
    NESTE_KJORING TIMESTAMP(3)                           NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IDX_JOBB_STATUS ON JOBB (STATUS, SAK_ID, BEHANDLING_ID, NESTE_KJORING);
-- Legger inn en unik index per type for en sak+behandling for åpne oppgaver
CREATE UNIQUE INDEX UIDX_JOBB_STATUS_SAK_BEHANDLING_TYPE ON JOBB (TYPE, SAK_ID, BEHANDLING_ID) WHERE (
    STATUS IN ('KLAR', 'FEILET') AND SAK_ID IS NOT NULL AND BEHANDLING_ID IS NOT NULL);

CREATE TABLE JOBB_HISTORIKK
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    JOBB_ID       BIGINT                                 NOT NULL REFERENCES JOBB (ID),
    STATUS        VARCHAR(50)                            NOT NULL,
    FEILMELDING   TEXT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IDX_JOBB_HISTORIKK_STATUS ON JOBB_HISTORIKK (JOBB_ID, STATUS);
