ALTER TABLE BREVBESTILLING
    ADD COLUMN BRUKER_IDENT VARCHAR(20);

CREATE TABLE SIGNATUR
(
    BREVBESTILLING_ID BIGINT NOT NULL REFERENCES BREVBESTILLING (ID),
    NAV_IDENT         VARCHAR(100) NOT NULL,
    ROLLE             VARCHAR(100) NOT NULL
);
