UPDATE SIGNATUR SET SORTERINGS_NOKKEL = 1 WHERE ROLLE = 'KVALITETSSIKRER';
UPDATE SIGNATUR SET SORTERINGS_NOKKEL = 2 WHERE ROLLE = 'SAKSBEHANDLER_OPPFOLGING';
UPDATE SIGNATUR SET SORTERINGS_NOKKEL = 3 WHERE ROLLE = 'BESLUTTER';
UPDATE SIGNATUR SET SORTERINGS_NOKKEL = 4 WHERE ROLLE = 'SAKSBEHANDLER_NASJONAL';

ALTER TABLE SIGNATUR
    ALTER COLUMN SORTERINGS_NOKKEL SET NOT NULL;