create table MOTTAKER
(
    ID                BIGSERIAL NOT NULL PRIMARY KEY,
    BREVBESTILLING_ID BIGINT    NOT NULL REFERENCES BREVBESTILLING (ID),
    IDENT             VARCHAR(20),
    IDENT_TYPE        VARCHAR(20),
    NAVN_OG_ADRESSE   jsonb,
    CONSTRAINT IDENT_ELLER_NAVN_OG_ADRESSE CHECK (
        (IDENT IS NOT NULL AND IDENT_TYPE IS NOT NULL AND NAVN_OG_ADRESSE IS NULL)
            OR
        (IDENT IS NULL AND IDENT_TYPE IS NULL AND NAVN_OG_ADRESSE IS NOT NULL)
        )
);

create table OPPRETTET_JOURNALPOST
(
    ID                         BIGSERIAL                              NOT NULL PRIMARY KEY,
    JOURNALPOST_ID             VARCHAR(40)                            NOT NULL,
    FERDIGSTILT                BOOLEAN                                NOT NULL DEFAULT FALSE,
    MOTTAKER_ID                BIGINT                                 NOT NULL REFERENCES MOTTAKER (ID),
    DISTRIBUSJON_BESTILLING_ID VARCHAR(40)                            NULL,
    OPPRETTET_TID              TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    OPPDATERT_TID              TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IDX_VEDLEGG_JOURNALPOST_ID ON VEDLEGG (JOURNALPOST_ID);
CREATE UNIQUE INDEX UIDX_OPPRETTET_JOURNALPOST_UNIK_REFERANSE ON OPPRETTET_JOURNALPOST (JOURNALPOST_ID);
