ALTER TABLE MOTTAKER
    ADD COLUMN TYPE TEXT NOT NULL DEFAULT 'HOVED';

UPDATE MOTTAKER M
SET TYPE = 'KOPI'
FROM BREVBESTILLING B
WHERE M.BREVBESTILLING_ID = B.ID
  AND M.BREVBESTILLING_ID IN (SELECT BREVBESTILLING_ID FROM MOTTAKER GROUP BY BREVBESTILLING_ID HAVING COUNT(*) > 1)
  AND (M.IDENT IS DISTINCT FROM B.BRUKER_IDENT);

ALTER TABLE MOTTAKER
    DROP CONSTRAINT IDENT_ELLER_NAVN_OG_ADRESSE;

ALTER TABLE MOTTAKER
    ADD CONSTRAINT UNIK_TYPE_PER_BREVBESTILLING UNIQUE (BREVBESTILLING_ID, TYPE);
