CREATE UNIQUE INDEX UIDX_OPPRETTET_JOURNALPOST_UNIK_MOTTAKER_ID ON OPPRETTET_JOURNALPOST (MOTTAKER_ID);
CREATE UNIQUE INDEX UIDX_MOTTAKER_UNIK_BREVBESTILLING_ID_IDENT ON MOTTAKER (BREVBESTILLING_ID, IDENT);
