ALTER TABLE MOTTAKER
    ADD COLUMN TYPE VARCHAR(20) NOT NULL DEFAULT 'HOVED';

ALTER TABLE MOTTAKER
    DROP CONSTRAINT IDENT_ELLER_NAVN_OG_ADRESSE;

ALTER TABLE MOTTAKER
    ADD CONSTRAINT UNIK_TYPE_PER_BREVBESTILLING UNIQUE (BREVBESTILLING_ID, TYPE);
