name: Deploy saksbehandling

on:
  push:
    branches: [ main ]
    paths-ignore:
        - '.github/pr.yaml'
        - '*.md'

jobs:
  build:
    permissions:
      contents: write
      actions: read
      checks: write
      id-token: write
    uses: navikt/aap-workflows/.github/workflows/gradle-build.yml@main
    secrets: inherit
    with:
      jdk: 22

  deploy-dev:
    needs: build
    permissions:
        contents: read
        id-token: write
    uses: navikt/aap-workflows/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      cluster: dev-gcp
      manifest: .nais/app.yaml
