name: Generer openapi schema

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/pr.yml'
      - '*.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      packages: write
      checks: write
      actions: write
      deployments: write
    steps:
      -   uses: actions/checkout@v4
      -   uses: actions/setup-java@v4.3.0
          with:
            java-version: 23
            distribution: 'temurin'
      -   name: Setup Gradle for a non-wrapper project
          uses: gradle/actions/setup-gradle@v4
          with:
            gradle-version: wrapper
      -   name: Bygg & test
          run: gradle :app:test --tests '*AppTest*.*openapi*' --continue --no-daemon --configuration-cache --stacktrace --info
      -   uses: actions/upload-artifact@v4
          id: artifact-upload-step
          with:
            name: openapi
            path: ./openapi.json
            overwrite: 'true'
      -   uses: actions/github-script@v7
          env:
            WORKFLOW_ID: ${{ inputs.workflow-id }}
            LABEL: ${{ inputs.label }}
          with:
            github-token: ${{ secrets.GH_WF_TOKEN }}
            script: |
              const fs = require('fs');
              await github.rest.actions.createWorkflowDispatch({
                  owner: 'navikt',
                  repo: 'aap-backend-typescript-types',
                  workflow_id: 'publish-and-release.yml',
                  ref: 'main',
                  inputs: {
                      'artifactId': '${{steps.artifact-upload-step.outputs.artifact-id}}',
                      'appNavn': 'brev'
                  }
              })