package no.nav.aap.brev.kontrakt

enum class Brevtype {
    INNVILGELSE,
    VEDTAK_11_18,
    AVSLAG,
    VARSEL_OM_BESTILLING,
    FORHÅNDSVARSEL_BRUDD_AKTIVITETSPLIKT,
    VEDTAK_11_7,
    VEDTAK_11_9,
    FORVALTNINGSMELDING,
    VEDTAK_ENDRING,
    KLAGE_AVVIST,
    KLAGE_OPPRETTHOLDELSE,
    KLAGE_TRUKKET,
    FORHÅNDSVARSEL_KLAGE_FORMKRAV
}