package no.nav.aap.brev.kontrakt

enum class Brevtype {
    INNVILGELSE,
    VEDTAK_UTVID_VEDTAKSLENGDE,
    VEDTAK_11_17,
    VEDTAK_11_18,
    AVSLAG,
    VARSEL_OM_BESTILLING,
    FORHÅNDSVARSEL_BRUDD_AKTIVITETSPLIKT,
    VEDTAK_11_7,
    VEDTAK_11_9,
    VEDTAK_11_23_SJETTE_LEDD,
    FORVALTNINGSMELDING,
    VEDTAK_ENDRING,
    BARNETILLEGG_SATS_REGULERING,
    KLAGE_AVVIST,
    KLAGE_OPPRETTHOLDELSE,
    KLAGE_TRUKKET,
    KLAGE_MOTTATT,
    FORHÅNDSVARSEL_KLAGE_FORMKRAV,
    OMGJØRING_VEDTAK_11_9
}