package no.nav.aap.brev.kontrakt

enum class Brevtype {
    INNVILGELSE,
    AVSLAG,
    VARSEL_OM_BESTILLING,
    FORHÅNDSVARSEL_BRUDD_AKTIVITETSPLIKT,
    FORVALTNINGSMELDING,
    VEDTAK_ENDRING,
    KLAGE_AVVIST,
    KLAGE_OPPRETTHOLDELSE,
    KLAGE_TRUKKET
}